'''
Each new term in the Fibonacci sequence is generated by
adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence
whose values do not exceed four million,
find the sum of the even-valued terms.
'''

def fibbonacci(n):
    if n <= 1:
        return n
    else:
        return fibbonacci(n-1) + fibbonacci(n-2)

my_sum = 0
n = int(input("Input Number of Terms: "))

print ("Fibbonacci sequence: ")
for i in range (n):
    while i % 2 == 0:
        print(fibbonacci(i))


